---
layout: cv
title: Victor Santana's CV
---
# Victor Santana
International computer engineering student with a strong interest in space technologies, software development, automation, and computer architecture. Seeking an internship in the summer of 2025.

<div id="webaddress">
<a href="victorrafaelsantana@hotmail.es">victorrafaelsantana@hotmail.es</a>
| <a href="https://www.linkedin.com/in/victorrafaelsantana/">My LinkedIn page</a>
</div>

### Specialized in

•	**Programming Languages (in order of proficiency):** C#, Python, C++, C, Assembly

•	**Management & Soft:** Scheduling, Team Management, Team Training, Spanish Language

•	**Hardware & Software Tools:** Arduino & IDE, STM32 & CubeIDE, GitHub

## Education

**Bachelor of Science in Computer Engineering**                                     |   September 2023 - December 2027

*Brigham Young University - Idaho*	                                                |   Rexburg, Idaho

•	Certificate: Machine Learning Fundamentals

•	Major 4.0 GPA, awarded BYU-Idaho's academic scholarship and IEEE Society Even Planner

•	Relevant Courses: Programming with Classes (C#), C, C++, Programming with Data Structures (C#), and Fundamentals Digital Systems, Microprocessor Based System Design, Data Science Programming

### Projects

**Food Storage Management System**                                                  |    November 2024 - Present

*C# | OOP | File Handling | Email Integration | Data Storing | Input Validation*	|    Rexburg, ID

•	Designed a food storage tracking system. Implemented an email notification system for expiration notifications and developed a robust input validation system for accurate data entry

•	Integrated a secure file handling for user data storage, and enhanced usability by integrating date parsing and improving data storage efficiency

•	Planned improvements: A more intuitive user interface and compiling program into an executable
 
**Expense Tracker**                                                                 |   January 2025 - Present

*C++ | File Handling | STL | Data Storing | Input Validation*	                    |   Rexburg, ID

•	Developed a C++ application to track, filter, and manage of expenses. Implemented file handling to save and load expenses efficiently in 1 file

•	Utilized STL algorithms for expense management, and built a menu-driven UI with input validation and error handling

•	Planned improvements: Sorting, editing, and deleting expenses, smart pointer integration


## Occupation

**Faculty Technology Center Lead**                                                   |   January 2025 - Present

*Brigham Young University - Idaho*                                                   |   Rexburg, Idaho

•	Enhanced 100+ online courses in Learning Management System (LMS) improving user experience, showcasing strong problem-solving skills to ensure high-quality course delivery

•	Collaborated in a dynamic team environment, utilizing various 5+ technologies to complete tasks efficiently and adapt to evolving project goals

•	Promoted to lead after 8 months of tenure, and built a training course and handbook for new hire training

<!-- ### Footer

Last updated: May 2013 -->